### ISSUE TITLE
uservars save to and load from hubot brain

### ISSUE THREAD

**Issue by changhaitravis** [aichaos/hubot-rivescript#2]
I found that if you tell rivescript stuff about you it would remember, but this won't be persisted across reboots. 

However, if getuservars and setuservars is exposed, we can use hubot.brain for persistence.

I'll be submitting a pull request with a thoroughly tested implementation of this over the weekend if it turns out to be possible/easy.

**Comment by changhaitravis** [comment]
#3 here we go. I probably could've just done the pull request instead of creating an issue though. I really want to see this feature get implemented upstream.

**Comment by kirsle** [comment]
I've published `hubot-rivescript v0.1.1` which incorporates this change.

**Comment by changhaitravis** [comment]
Nice, I couldn't figure out coffeescript scoping, and I was reverse engineering the hubot brain interactions from another script that works directly with the data object. Thanks for cleaning it up
